[project]
name = "crawleragent"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "gradio>=6.24.0",
    "openai>=3.1.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true
